# Generated by Django 4.1.5 on 2023-01-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_vancancy_job_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experency',
            new_name='experience',
        ),
    ]
