# Generated by Django 4.1.5 on 2023-01-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
